FROM python:3.11.3-slim-buster

WORKDIR /app

COPY manage.py manage.py
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./app /app/app

ENV STAGE=Dev

RUN aws dynamodb list-tables --endpoint-url http://host.docker.internal:8000

CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0"]